version: 2

sources:
  - name: staging
    database: useful-monitor-415110
    schema: health_analysis_dataset

    tables:
      - name: hourly_calories
      - name: hourly_intensities
      - name: hourly_steps

models:
  - name: stg_hourly_steps
    description: "Number of steps walked during each hour of the day for each user. Each 24-hour period is divided into hourly intervals."
    columns:
      - name: id
        data_type: int64
        description: "Id of users. It is unique only when combined with the activity hour."
        tests:
          - not_null:
              severity: warn 

      - name: activityhour
        data_type: timestamp
        description: "The hour during which the steps were recorded. For example: 2016-04-13 00:00 UTC."

      - name: steptotal
        data_type: int64
        description: "The number of steps walked during each hour."

  - name: stg_hourly_intensities
    description: "Total and average intensity (total intensity divided by 60 minutes) during each hour of the day for each user."
    columns:
      - name: id
        data_type: int64
        description: "Id of users. It is unique only when combined with the activity hour."
        tests:
          - not_null:
              severity: warn

      - name: activityhour
        data_type: timestamp
        description: "The hour during which the intensity was recorded. For example: 2016-04-13 00:00 UTC."

      - name: totalintensity
        data_type: int64
        description: "The total intensity recorded during each hour."

      - name: averageintensity
        data_type: float64
        description: "The average intensity recorded during each hour."

  - name: stg_hourly_calories
    description: "Total calories burned during each hour of the day for each user."
    columns:
      - name: id
        data_type: int64
        description: "Id of users. It is unique only when combined with the activity hour."
        tests:
          - not_null:
              severity: warn

      - name: activityhour
        data_type: timestamp
        description: "The hour during which the calories were recorded. For example: 2016-04-13 00:00 UTC."

      - name: calories
        data_type: int64
        description: "The total calories burned during each hour."
